templates:
  - reference: order
    name: Order
    fields:
      - reference: order_number
        name: Order No.
        type: StandardProcedure::FieldDefinition::Text
      - reference: product
        name: Product
        type: StandardProcedure::FieldDefinition::Dropdown
        options:
          - Birth Certificate
          - Death Certificate
          - Marriage Certificate
          - Divorce Certificate
      - reference: first_name
        name: First name
        type: StandardProcedure::FieldDefinition::Text
      - reference: last_name
        name: Last name
        type: StandardProcedure::FieldDefinition::Text
      - reference: gro
        name: GRO
        type: StandardProcedure::FieldDefinition::Reference
        options: suppliers
      - reference: gro_reference
        name: GRO Reference
        type: StandardProcedure::FieldDefinition::Text
      - reference: gro_notes
        name: Notes
        type: StandardProcedure::FieldDefinition::RichText
slot_definitions:
form_templates:
roles:
  - reference: manager
    name: Manager
    access_level: administrator
  - reference: staff_member
    name: Staff member
  - reference: api_user
    name: API user
  - reference: customer
    name: Customer
    access_level: restricted
    field_definitions:
      - reference: address
        name: Address
        type: Address
        mandatory: true
        visible_to: all
        editable_by: manager
      - reference: postcode
        name: Post code
        type: Postcode
        mandatory: true
        visible_to: all
        editable_by: manager
  - reference: registry_office
    name: Registry Office
    access_level: restricted
groups:
  - reference: api_users
    name: API
  - reference: employees
    name: Employee
  - reference: customers
    name: Customer
  - reference: suppliers
    name: supplier
workflows:
  - reference: order_processing
    name: Order processing
    type: Board
    statuses:
      - reference: incoming_order
        name: Incoming
        type: List
        assign_to: nichola@example.com
        alerts:
          - hours: 24
            type: StandardProcedure::Alert::SendNotification
            contacts:
              - nichola@example.com
        actions:
          - reference: reassign
            name: Reassign
            type: StandardProcedure::WorkflowAction::Reassignment
          - reference: place_order_with_gro
            name: Place order with GRO
            type: Store::PlaceOrderWithGro
          - reference: send_message
            name: Send message
            type: StandardProcedure::WorkflowAction::Message
          - reference: postpone
            name: Postpone
            type: StandardProcedure::WorkflowAction::Postponement
          - reference: cancel
            name: Cancel
            type: StandardProcedure::WorkflowAction::Cancellation
      - reference: order_placed
        name: Order placed
        type: List
        alerts:
          - hours: 120
            type: StandardProcedure::Alert::SendNotification
            contacts:
              - nichola@example.com
        actions:
          - name: Reassign
            type: StandardProcedure::WorkflowAction::Reassignment
          - reference: order_received_from_gro
            name: Order received from GRO
            outcomes:
              - type: StandardProcedure::WorkflowAction::ChangeStatus
                status: requires_dispatch
          - name: Send message
            type: StandardProcedure::WorkflowAction::Message
          - name: Place on hold
            type: StandardProcedure::WorkflowAction::Postponement
          - name: Cancel
            type: StandardProcedure::WorkflowAction::Cancellation
      - reference: requires_dispatch
        name: Requires Dispatch
        type: List
        alerts:
          - hours: 24
            type: StandardProcedure::Action::SendNotification
            contacts: 
              - nichola@example.com
        actions:
          - name: Reassign
            type: StandardProcedure::WorkflowAction::Reassignment
          - reference: mark_as_dispatched
            name: Dispatch
            outcomes:
              - StandardProcedure::WorkflowAction::ChangeStatus
              - status: dispatched
          - name: Send message
            type: StandardProcedure::WorkflowAction::Message
          - name: Place on hold
            type: StandardProcedure::WorkflowAction::Postponement
          - name: Cancel
            type: StandardProcedure::WorkflowAction::Cancellation
      - reference: dispatched
        name: Out for delivery
        type: List
        alerts:
          - hours: 120 
            type: StandardProcedure::Action::SendNotification
            contacts: 
              - nichola@example.com
        actions:
          - name: Complete
            type: StandardProcedure::WorkflowAction::Completion
          - name: Send message
            type: StandardProcedure::WorkflowAction::Message
