templates:
  - reference: order
    name: Order
    fields:
      - reference: order_number
        name: Order No.
        type: StandardProcedure::FieldDefinition::Text
      - reference: product
        name: Product
        type: StandardProcedure::FieldDefinition::Dropdown
        options:
          - Birth Certificate
          - Death Certificate
          - Marriage Certificate
          - Divorce Certificate
      - reference: first_name
        name: First name
        type: StandardProcedure::FieldDefinition::Text
      - reference: last_name
        name: Last name
        type: StandardProcedure::FieldDefinition::Text
      - reference: gro
        name: GRO
        type: StandardProcedure::FieldDefinition::Reference
        options: suppliers
      - reference: gro_reference
        name: GRO Reference
        type: StandardProcedure::FieldDefinition::Text
      - reference: gro_notes
        name: Notes
        type: StandardProcedure::FieldDefinition::RichText
slot_definitions:
form_templates:
roles:
  - reference: manager
    name: Manager
    access_level: administrator
  - reference: staff_member
    name: Staff member
  - reference: api_user
    name: API user
  - reference: customer
    name: Customer
    access_level: restricted
    field_definitions:
      - reference: address
        name: Address
        type: Address
        mandatory: true
        visible_to: all
        editable_by: manager
      - reference: postcode
        name: Post code
        type: Postcode
        mandatory: true
        visible_to: all
        editable_by: manager
  - reference: registry_office
    name: Registry Office
    access_level: restricted
groups:
  - reference: api_users
    name: API
  - reference: employees
    name: Employee
  - reference: customers
    name: Customer
  - reference: suppliers
    name: supplier
workflows:
  - reference: order_processing
    name: Order processing
    type: Board
    statuses:
      - reference: incoming_order
        name: Incoming
        type: List
        assign_to: nichola@example.com
        alerts:
          - hours: 24
            type: StandardProcedure::Alert::SendNotification
            contacts:
              - nichola@example.com
        actions:
          - reference: reassign
            name: Reassign
            type: StandardProcedure::WorkflowItem::Reassignment
          - reference: place_order_with_gro
            name: Place order with GRO
            required_fields:
              - gro
              - gro_reference
              - gro_notes
          - reference: send_message
            name: Send message
            type: StandardProcedure::WorkflowItem::Message
          - reference: postpone
            name: Postpone
            type: StandardProcedure::WorkflowItem::Postponement
          - reference: cancel
            name: Cancel
            type: StandardProcedure::WorkflowItem::Cancellation
      - reference: order_placed
        name: Order placed
        type: List
        card_types:
          standard_order:
            - deadline:
                - hours: 120
                - recipient: nichola@example.com
                - type: StandardProcedure::Deadline::SendNotification
          priority_order:
            - assign_to: anna@example.com
            - deadline:
                - hours: 48
                - recipient: anna@example.com
                - type: StandardProcedure::Deadline::SendNotification
        actions:
          - name: Reassign
            type: StandardProcedure::WorkflowItem::Reassignment
            permissions:
              - employees
          - reference: order_received_from_gro
            name: Order received from GRO
            permissions:
              - employees
            outcomes:
              - type: StandardProcedure::WorkflowItem::ChangeStatus
                status: requires_dispatch
          - name: Send message
            type: StandardProcedure::WorkflowItem::Message
            permissions:
              - employees
              - owner
          - name: Place on hold
            type: StandardProcedure::WorkflowItem::Postponement
            permissions:
              - employees
          - name: Cancel
            type: StandardProcedure::WorkflowItem::Cancellation
            permissions:
              - employees
              - owner
      - reference: requires_dispatch
        name: Requires Dispatch
        type: List
        card_types:
          standard_order:
            - deadline:
                - hours: 24
                - recipient: nichola@example.com
                - type: StandardProcedure::Deadline::SendNotification
          priority_order:
            - assign_to: anna@example.com
            - deadline:
                - hours: 8
                - recipient: anna@example.com
                - type: StandardProcedure::Deadline::SendNotification
        actions:
          - name: Reassign
            type: StandardProcedure::WorkflowItem::Reassignment
            permissions:
              - employees
          - reference: mark_as_dispatched
            name: Dispatch
            field_definitions:
              - reference: dispatch_notes
                name: Notes
                type: RichText
            permissions:
              - employees
            outcomes:
              - StandardProcedure::WorkflowItem::ChangeStatus
              - status: dispatched
          - name: Send message
            type: StandardProcedure::WorkflowItem::Message
            permissions:
              - employees
              - owner
          - name: Place on hold
            type: StandardProcedure::WorkflowItem::Postponement
            permissions:
              - employees
          - name: Cancel
            type: StandardProcedure::WorkflowItem::Cancellation
            permissions:
              - employees
      - reference: dispatchewd
        name: Out for delivery
        type: List
        card_types:
          standard_order:
            - deadline:
                - hours: 120
                - type: StandardProcedure::Deadline::CompleteItem
          priority_order:
            - assign_to: anna@example.com
            - deadline:
                - hours: 48
                - recipient: anna@example.com
                - type: StandardProcedure::Deadline::SendNotification
        actions:
          - name: Complete
            type: StandardProcedure::WorkflowItem::Complete
            permissions:
              - employees
          - name: Send message
            type: StandardProcedure::WorkflowItem::Message
            permissions:
              - employees
              - owner
